apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"admin","namespace":"vkr"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"admin"}},"template":{"metadata":{"labels":{"app":"admin"}},"spec":{"containers":[{"env":[{"name":"SPRING_DATASOURCE_URL","valueFrom":{"configMapKeyRef":{"key":"SPRING_DATASOURCE_URL","name":"vkr-config"}}},{"name":"SPRING_DATASOURCE_USERNAME","valueFrom":{"configMapKeyRef":{"key":"SPRING_DATASOURCE_USERNAME","name":"vkr-config"}}},{"name":"SPRING_DATASOURCE_PASSWORD","valueFrom":{"secretKeyRef":{"key":"SPRING_DATASOURCE_PASSWORD","name":"vkr-secrets"}}},{"name":"SERVER_PORT","valueFrom":{"configMapKeyRef":{"key":"SERVER_PORT_ADMIN","name":"vkr-config"}}},{"name":"APP_ADMIN_USERNAME","valueFrom":{"configMapKeyRef":{"key":"APP_ADMIN_USERNAME","name":"vkr-config"}}},{"name":"ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"ADMIN_PASSWORD","name":"vkr-secrets"}}}],"image":"vkr/admin:1.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/admin","port":8082},"initialDelaySeconds":40,"periodSeconds":20},"name":"admin","ports":[{"containerPort":8082}],"readinessProbe":{"httpGet":{"path":"/admin","port":8082},"initialDelaySeconds":20,"periodSeconds":10}}]}}}}
  creationTimestamp: "2025-12-29T10:05:55Z"
  generation: 1
  name: admin
  namespace: vkr
  resourceVersion: "5893"
  uid: a95bb431-5d4c-41f2-985a-410353a31296
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: admin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATASOURCE_URL
              name: vkr-config
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATASOURCE_USERNAME
              name: vkr-config
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SPRING_DATASOURCE_PASSWORD
              name: vkr-secrets
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              key: SERVER_PORT_ADMIN
              name: vkr-config
        - name: APP_ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              key: APP_ADMIN_USERNAME
              name: vkr-config
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ADMIN_PASSWORD
              name: vkr-secrets
        image: vkr/admin:1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: admin
        ports:
        - containerPort: 8082
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /admin
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-29T10:06:17Z"
    lastUpdateTime: "2025-12-29T10:06:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-29T10:05:55Z"
    lastUpdateTime: "2025-12-29T10:06:17Z"
    message: ReplicaSet "admin-678878dd89" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
