apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"catalog","namespace":"vkr"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"catalog"}},"template":{"metadata":{"labels":{"app":"catalog"}},"spec":{"containers":[{"env":[{"name":"SPRING_DATASOURCE_URL","valueFrom":{"configMapKeyRef":{"key":"SPRING_DATASOURCE_URL","name":"vkr-config"}}},{"name":"SPRING_DATASOURCE_USERNAME","valueFrom":{"configMapKeyRef":{"key":"SPRING_DATASOURCE_USERNAME","name":"vkr-config"}}},{"name":"SPRING_DATASOURCE_PASSWORD","valueFrom":{"secretKeyRef":{"key":"SPRING_DATASOURCE_PASSWORD","name":"vkr-secrets"}}},{"name":"SERVER_PORT","valueFrom":{"configMapKeyRef":{"key":"SERVER_PORT_CATALOG","name":"vkr-config"}}}],"image":"vkr/catalog:1.0","imagePullPolicy":"IfNotPresent","name":"catalog","ports":[{"containerPort":8081}],"readinessProbe":{"httpGet":{"path":"/","port":8081},"initialDelaySeconds":15,"periodSeconds":10}}]}}}}
  creationTimestamp: "2025-12-29T10:05:55Z"
  generation: 1
  name: catalog
  namespace: vkr
  resourceVersion: "5898"
  uid: 57fee171-af22-418d-a3e7-cfd7c93c1b46
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: catalog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATASOURCE_URL
              name: vkr-config
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SPRING_DATASOURCE_USERNAME
              name: vkr-config
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SPRING_DATASOURCE_PASSWORD
              name: vkr-secrets
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              key: SERVER_PORT_CATALOG
              name: vkr-config
        image: vkr/catalog:1.0
        imagePullPolicy: IfNotPresent
        name: catalog
        ports:
        - containerPort: 8081
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-29T10:06:18Z"
    lastUpdateTime: "2025-12-29T10:06:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-29T10:05:55Z"
    lastUpdateTime: "2025-12-29T10:06:18Z"
    message: ReplicaSet "catalog-65f6fb9cbc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
