apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"postgres","namespace":"vkr"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"postgres"}},"template":{"metadata":{"labels":{"app":"postgres"}},"spec":{"containers":[{"env":[{"name":"POSTGRES_DB","value":"redgmapp"},{"name":"POSTGRES_USER","value":"redgmapp"},{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"SPRING_DATASOURCE_PASSWORD","name":"vkr-secrets"}}}],"image":"postgres:16","name":"postgres","ports":[{"containerPort":5432}],"readinessProbe":{"exec":{"command":["sh","-c","pg_isready -U redgmapp -d redgmapp"]},"initialDelaySeconds":5,"periodSeconds":5}}]}}}}
  creationTimestamp: "2025-12-29T10:05:55Z"
  generation: 1
  name: postgres
  namespace: vkr
  resourceVersion: "5866"
  uid: 0ddeffbe-a5ea-416f-84bd-7ec6c13b34b0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: redgmapp
        - name: POSTGRES_USER
          value: redgmapp
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SPRING_DATASOURCE_PASSWORD
              name: vkr-secrets
        image: postgres:16
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U redgmapp -d redgmapp
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-29T10:06:02Z"
    lastUpdateTime: "2025-12-29T10:06:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-29T10:05:55Z"
    lastUpdateTime: "2025-12-29T10:06:02Z"
    message: ReplicaSet "postgres-7848d869" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
